sudo: false
language: node_js
notifications:
  email: false
cache:
  - node_modules
node_js:
  - '7'
install:
  - npm install
before_script:
  - npm run lint
script:
  - npm test
branches:
  only:
    - "master"
